kafka:
  bootstrap-servers: localhost:9092
  properties:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.ewm.serializer.AvroSerializer

    consumer:
      client-id: UserActionConsumer
      group-id: userAction.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.ewm.deserializer.AvroDeserializer
      enable-auto-commit: false
      poll-timeout: 1000
  topics:
    user-action: stats.user-actions.v1