services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats
  event-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=event
      - POSTGRES_USER=event
      - POSTGRES_DB=event-db
  user-db:
    image: postgres:16.1
    container_name: postgres-user-service-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user-db
  request-db:
    image: postgres:16.1
    container_name: postgres-request-service-db
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_PASSWORD=request
      - POSTGRES_USER=request
      - POSTGRES_DB=request-db
  comment-db:
    image: postgres:16.1
    container_name: postgres-comment-service-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=comment
      - POSTGRES_USER=comment
      - POSTGRES_DB=comment-db