grpc:
  server:
    port: 0

kafka:
  producer:
    properties:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.practicum.ewm.serializer.AvroSerializer
  topic: stats.user-actions.v1