server:
  port: 0

spring:
  application:
    name: stat-server
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stat
    username: postgres
    password: 52458

eureka:
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka