server:
  port: 0

client:
  url: http://localhost:9090

spring:
  application:
    name: ewm-server
  jpa:
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: 52458

eureka:
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka