server:
  port: 0

spring:
  application:
    name: ewm-server
  jpa:
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      format_sql=true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main
    username: main
    password: main

eureka:
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka